DEBUG: True
EXP_NAME: 'End2End lens design for image restoration.'

lens:
  path: './lenses/cooke40_inferior.json'
  lr: !!python/tuple [1e-4, 1e-4, 0, 0]

network:
  pretrained: False
  lr: !!float 1e-2

train:
  train_dir: './datasets/DIV2K_train_HR'
  warm_up: 0.5
  epochs: 10
  bs: 4
  img_res: !!python/tuple [256, 256]

  noise: 0.001
  seed: 26
  depth: -10000